version: '3.5'

services:
  nginx-coffee-shop:
    container_name: nginx-coffee-shop
    image: nginx:1.22
    restart: "no"
    ports:
      - "84:80"
    volumes:
      - .:/var/www/
      - ./.docker/config/nginx/:/etc/nginx/conf.d/
      - ./.docker/logs/nginx:/var/log/nginx/
    networks:
      - web-network-coffee-shop

  php-coffee-shop:
    build:
      context: ./.docker
    container_name: php-coffee-shop
    restart: "no"
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - web-network-coffee-shop

  mysql-coffee-shop:
    container_name: mysql-coffee-shop
    image: mysql:latest
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - ./logs/mysql/:/var/logs/mysql
      - db-coffee-shop:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: coffee-shop
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - web-network-coffee-shop

  redis-coffee-shop:
    container_name: redis-coffee-shop
    image: redis:7.0.5
    ports:
      - "6380:6379"
    networks:
      - web-network-coffee-shop

volumes:
    db-coffee-shop:
        name: db-coffee-shop

networks:
  web-network-coffee-shop:
    driver: bridge
